[package]
name = "common"
description = "Common stuff like Diesel schemas and models are stored here for the entire emote tracking service"
version.workspace = true
authors.workspace = true
publish.workspace = true
repository.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
diesel = { version = "2.1.4", features = ["chrono", "postgres"] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
